### ISSUE TITLE
`compile_with_input()` holding onto memory even after completion

### ISSUE THREAD

**Issue by quangnguyen09** [Relacibo/typst-as-lib#8]
I've been using the crate and I've noticed memory continues to grow indefinitely after every call to `compile_with_input()`. I tested it with the code in `small_example.rs` by running it with a loop inside a docker container and monitoring the memory usage of the container.

```
fn main() {
    loop {
        let mut template = TypstTemplate::new(vec![Font::new(Bytes::from(FONT), 0).expect("Could not parse font!")], TEMPLATE_FILE);

        let mut doc = template
            .compile_with_input(Content{ v: vec![] })
            .output
            .expect("typst::compile() returned an error!");
    };
}
```

The memory usage increases much quicker if I compile with unique input data like `Utc::now().to_string()`.

**Comment by quangnguyen09** [comment]
I think I found the issue. It's because `typst::eval()` is memoized. So by clearing the cache with `comemo::evict(0)` after compiling, I was able to keep memory stable.

**Comment by Relacibo** [comment]
Oh cool. Yes I realized, that it was a problem with comemo the moment you posted that comment. 😂

**Comment by quangnguyen09** [comment]
Yeah lol. I didn't realize the typst crate caches. Anyway, thank you for your work on this project!

**Comment by Relacibo** [comment]
Yeah, not only does the memory consumption grow for nearly every compilation. It also slows down a lot. I will look for a solution in my crate now....
